export const wordList = [
  { word: "guitar", hint: "A musical instrument.", category: "other" },
  { word: "Barcelona", hint: "City in Spain and a football club.", category: "city" },
  { word: "mountain", hint: "A large natural elevation of the Earth's surface.", category: "other" },
  { word: "painting", hint: "An art form using colors on a surface to create images or expression.", category: "other" },
  { word: "astronomy", hint: "The scientific study of celestial objects and phenomena.", category: "other" },
  { word: "football", hint: "A popular sport.", category: "other" },
  { word: "chocolate", hint: "Food that kids love the most.", category: "other" },
  { word: "cake", hint: "Birthdays...", category: "other" },
  { word: "history", hint: "The study of past events and human civilization.", category: "other" },
  { word: "pizza", hint: "A savory dish consisting of a round, flattened base with toppings.", category: "other" },
  { word: "camera", hint: "A device used to capture and record images or videos.", category: "other" },
  { word: "diamond", hint: "A precious gemstone known for its brilliance and hardness.", category: "other" },
  { word: "Oslo", hint: "The capital of Norway.", category: "city" },
  { word: "bicycle", hint: "A human-powered vehicle with two wheels.", category: "other" },
  { word: "sunset", hint: "The daily disappearance of the sun below the horizon.", category: "other" },
  { word: "coffee", hint: "A popular caffeinated beverage made from roasted coffee beans.", category: "other" },
  { word: "dance", hint: "A rhythmic movement of the body often performed to music.", category: "other" },
  { word: "galaxy", hint: "A vast system of stars, gas, and dust held together by gravity.", category: "other" },
  { word: "volcano", hint: "A mountain or hill with a vent through which lava, rock fragments, hot vapor, and gas are ejected.", category: "other" },
  { word: "Madrid", hint: "The capital of Spain.", category: "city" },
  { word: "basketball", hint: "Sport - shooting a ball into a hoop.", category: "other" },
  { word: "architecture", hint: "The art and science of designing and constructing buildings.", category: "other" },
  { word: "ballet", hint: "A classical dance form characterized by precise and graceful movements.", category: "other" },
  { word: "astronaut", hint: "A person trained to travel and work in space.", category: "other" },
  { word: "waterfall", hint: "A cascade of water falling from a height.", category: "other" },
  { word: "technology", hint: "The application of scientific knowledge for practical purposes.", category: "other" },
  { word: "rainbow", hint: "A meteorological phenomenon caused by reflection, refraction, and dispersion of light.", category: "other" },
  { word: "Paris", hint: "The capital of France.", category: "city" },
  { word: "piano", hint: "A musical instrument played by pressing keys that cause hammers to strike strings.", category: "other" },
  { word: "vacation", hint: "A period of time devoted to pleasure, rest, or relaxation.", category: "other" },
  { word: "theater", hint: "A building or outdoor area in which plays, movies, or other performances are staged.", category: "other" },
  { word: "telephone", hint: "A device used to transmit sound over long distances.", category: "other" },
  { word: "language", hint: "A system of communication consisting of words, gestures, and syntax.", category: "other" },
  { word: "desert", hint: "A barren or arid land with little or no precipitation.", category: "other" },
  { word: "sunflower", hint: "A tall plant with a large yellow flower head.", category: "other" },
  { word: "fantasy", hint: "A genre of imaginative fiction involving magic and supernatural elements.", category: "other" },
  { word: "telescope", hint: "An optical instrument used to view distant objects in space.", category: "other" },
  { word: "photography", hint: "The art, process, or practice of creating images by recording light or other electromagnetic radiation.", category: "other" },
  { word: "planet", hint: "A celestial body that orbits a star and does not produce light of its own.", category: "other" },
  { word: "river", hint: "A large natural stream of water flowing in a channel to the sea, a lake, or another such stream.", category: "other" },
  { word: "mysterious", hint: "Difficult or impossible to understand, explain, or identify.", category: "other" },
  { word: "enigma", hint: "Something that is mysterious, puzzling, or difficult to understand.", category: "other" },
  { word: "puzzle", hint: "A game, toy, or problem designed to test ingenuity or knowledge.", category: "other" },
  { word: "whisper", hint: "To speak very softly or quietly, often in a secretive manner.", category: "other" },
  { word: "shadow", hint: "A dark area or shape produced by an object blocking the light.", category: "other" },
  { word: "secret", hint: "Something kept hidden or unknown to others.", category: "other" },
  { word: "curiosity", hint: "A strong desire to know or learn something.", category: "other" },
  { word: "moonlight", hint: "The light from the moon.", category: "other" },
  { word: "school", hint: "An institution for educating children.", category: "other" },
  { word: "banana", hint: "A long curved fruit with a yellow skin.", category: "other" },
  { word: "computer", hint: "An electronic device for storing and processing data.", category: "other" },
  { word: "quicksand", hint: "A deep, soft, wet area of sand that sucks down anything on it.", category: "other" },
  { word: "paradox", hint: "A statement that contradicts itself but may still be true.", category: "other" },
  { word: "quarantine", hint: "A period of isolation imposed on people, animals, or things to prevent the spread of disease or pests.", category: "other" },
  { word: "eclipse", hint: "An astronomical event where one celestial body moves into the shadow of another.", category: "other" },
  { word: "captain", hint: "The person in command of a ship, aircraft, or sports team.", category: "other" },
  { word: "festival", hint: "A day or period of celebration, typically for religious reasons.", category: "other" },
  { word: "horizon", hint: "The line where the earth's surface and the sky appear to meet.", category: "other" },
  { word: "journey", hint: "An act of traveling from one place to another.", category: "other" },
  { word: "gallery", hint: "A room or building for the display or sale of works of art.", category: "other" },
  { word: "treasure", hint: "A quantity of precious metals, gems, or other valuable objects.", category: "other" },
  { word: "sculptor", hint: "An artist who carves or molds figures from materials like stone, metal, or clay.", category: "other" },
  { word: "avalanche", hint: "A mass of snow, ice, and rocks falling rapidly down a mountainside.", category: "other" },
  { word: "heritage", hint: "Property or traditions passed down from previous generations.", category: "other" },
  { word: "mineral", hint: "A solid, naturally occurring inorganic substance.", category: "other" },
  { word: "triangle", hint: "A three-sided polygon.", category: "other" },
  { word: "alphabet", hint: "A set of letters or symbols in a fixed order used to represent the basic sounds of a language.", category: "other" },
  { word: "vacuum", hint: "A space entirely devoid of matter.", category: "other" },
  { word: "embrace", hint: "To hold someone closely in one's arms.", category: "other" },
  { word: "monument", hint: "A structure erected to commemorate persons or events.", category: "other" },
  { word: "calendar", hint: "A system by which the beginning, length, and subdivisions of the year are fixed.", category: "other" },
  { word: "portrait", hint: "A painting, drawing, photograph, or engraving of a person.", category: "other" },
  { word: "diameter", hint: "A straight line passing through the center of a circle.", category: "other" },
  { word: "voltage", hint: "An electromotive force or potential difference expressed in volts.", category: "other" },
  { word: "Lion", hint: "A large, wild cat known for its majestic mane.", category: "animal" },
  { word: "Elephant", hint: "The largest land animal, known for its trunk.", category: "animal" },
  { word: "Giraffe", hint: "An animal with a long neck and legs, native to Africa.", category: "animal" },
  { word: "Kangaroo", hint: "A marsupial known for its powerful hind legs and tail.", category: "animal" },
  { word: "Panda", hint: "A large bear-like animal known for its black and white fur.", category: "animal" },
  { word: "Russia", hint: "The largest country in the world by area.", category: "country" },
  { word: "Japan", hint: "An island nation in East Asia.", category: "country" },
  { word: "Brazil", hint: "The largest country in South America.", category: "country" },
  { word: "Egypt", hint: "A country known for its ancient pyramids.", category: "country" },
  { word: "Australia", hint: "A country and continent known for its unique wildlife and landscapes.", category: "country" },
  { word: "New York", hint: "A major city in the USA known for its iconic skyline.", category: "city" },
  { word: "Tokyo", hint: "The capital city of Japan.", category: "city" },
  { word: "Sydney", hint: "A major city in Australia known for its opera house and harbor.", category: "city" },
  { word: "Rome", hint: "The capital city of Italy, known for its ancient history.", category: "city" },
  { word: "Berlin", hint: "The capital city of Germany.", category: "city" },
  { word: "Canada", hint: "A country known for its maple syrup and cold winters.", category: "country" },
  { word: "India", hint: "A country known for its diverse culture and Bollywood.", category: "country" },
  { word: "Argentina", hint: "A country known for its tango dance and beef.", category: "country" },
  { word: "South Africa", hint: "A country known for its wildlife and Nelson Mandela.", category: "country" },
  { word: "Mexico", hint: "A country known for its vibrant culture and cuisine.", category: "country" },
  { word: "Sweden", hint: "A Scandinavian country known for its high standard of living.", category: "country" },
  { word: "Thailand", hint: "A country known for its beaches and Buddhist temples.", category: "country" },
  { word: "Turkey", hint: "A country straddling Europe and Asia, known for its rich history.", category: "country" },
  { word: "Greece", hint: "A country known for its ancient ruins and islands.", category: "country" },
  { word: "Norway", hint: "A country known for its fjords and Northern Lights.", category: "country" },
  { word: "Penguin", hint: "A flightless bird that lives in the Southern Hemisphere.", category: "animal" },
  { word: "Shark", hint: "A large predatory fish found in oceans.", category: "animal" },
  { word: "Eagle", hint: "A bird of prey known for its powerful talons and keen eyesight.", category: "animal" },
  { word: "Dolphin", hint: "A highly intelligent marine mammal known for its playful behavior.", category: "animal" },
  { word: "Tiger", hint: "A large, striped wild cat native to Asia.", category: "animal" },
  { word: "Bear", hint: "A large mammal found in various parts of the world, including forests and mountains.", category: "animal" },
  { word: "Wolf", hint: "A wild carnivorous mammal that lives in packs.", category: "animal" },
  { word: "Koala", hint: "A marsupial native to Australia, known for its tree-dwelling lifestyle.", category: "animal" },
  { word: "Ostrich", hint: "The largest living bird, native to Africa.", category: "animal" },
  { word: "Hawk", hint: "A bird of prey known for its hunting skills and keen vision.", category: "animal" },
  { word: "Istanbul", hint: "A major city in Turkey known for its historical sites.", category: "city" },
  { word: "Dubai", hint: "A city in the UAE known for its modern architecture and luxury.", category: "city" },
  { word: "Lisbon", hint: "The capital city of Portugal, known for its colorful streets.", category: "city" },
  { word: "Vienna", hint: "The capital city of Austria, known for its classical music heritage.", category: "city" },
  { word: "Seoul", hint: "The capital city of South Korea, known for its technology and culture.", category: "city" },
  { word: "Buenos Aires", hint: "The capital city of Argentina, known for its European-style architecture.", category: "city" },
  { word: "Cairo", hint: "The capital city of Egypt, known for its proximity to the pyramids.", category: "city" },
  { word: "Reykjavik", hint: "The capital city of Iceland, known for its geothermal activity.", category: "city" },
  { word: "Hong Kong", hint: "A major city known for its skyline and harbor.", category: "city" },
  { word: "Athens", hint: "The capital city of Greece, known for its ancient history.", category: "city" },
];
